import 'package:flutter/material.dart';

import '../../../../../design_system/alera_colors.dart';
import '../../../../../design_system/alera_typography.dart';
import '../../../../../design_system/widgets/alera_card.dart';

/// A short, plain-language recap of the period shown in the chart above it
/// (e.g. "Heart rate stayed in the normal range for 5 of 6 periods...").
///
/// The text is computed locally from the same stats already on screen -
/// see each page's `_trendSummaryText` helper - rather than generated by a
/// model, so this card intentionally carries no "AI" labeling. Once a real
/// summary endpoint exists, only those helpers need to change; this widget
/// can stay as-is.
class TrendSummaryCard extends StatelessWidget {
  final String text;

  const TrendSummaryCard({super.key, required this.text});

  @override
  Widget build(BuildContext context) {
    return AleraCard(
      key: const Key('trend-summary-card'),
      padding: const EdgeInsets.all(16),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 36,
            height: 36,
            decoration: const BoxDecoration(
              color: AleraColors.primarySoft,
              shape: BoxShape.circle,
            ),
            alignment: Alignment.center,
            child: const Icon(
              Icons.auto_awesome,
              size: 18,
              color: AleraColors.primary,
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Trend summary',
                  style: AleraTypography.sectionTitle.copyWith(fontSize: 16),
                ),
                const SizedBox(height: 4),
                Text(
                  text,
                  style: AleraTypography.body.copyWith(
                    fontSize: 13,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
